### ISSUE TITLE
Docker Settings

### ISSUE THREAD

**Issue by rocky4546** [rocky4546/tvheadend-locast#6]
The .alpine and .slim-buster Docker file gives the following error:
`ERROR: Config file missing, Exiting...`
Adding the following line to either makes the docker run without error.
`COPY *.ini /app/`
Question is... how is it working for the developers when it seems to be missing the line?

**Comment by rocky4546** [comment]
This issue is to mainly determine the end structure to use to support the different environments especially docker.

As for folder structure, an effective docker container would provide the static files to the /apps area while providing the data and cache area that changes to an area mounted externally.  Since the configuration definition files are static, they should be moved into the lib folder.  I recommend placing them into a resource folder that would contain other resources such as a language area.  The other non-python area is the web area that contains the html, javascript, images, and css files that are directly provided to the web port.

The web interface is unique, in that, it also contains dynamic files that are created based on other data.  These could be templates or even python CGI type files.  It would make sense to place the dynamic files somewhere near the web static files.

The config.ini file should be searched in the ./data area or the top level folder, but since the data area is unknown until after the config file is loaded, the config.ini file path must be passed into the application as an argument if not in a default location.

**Comment by rocky4546** [comment]
Here is what I have determine. With the Dockerfile NOT containing the ini file, the following command can be used once the container is built.
`sudo docker run -p 6077:6077 -v [location of the data area]:/app/data -rm tvh8.0.0-alpha001`
This command will run the docker app with the data folder containing the data files from an external mount point.  This allows for the data and cache to be updated.  Note the config.ini file is located in the data folder. The 6077:6077 also provides an external port so the website can be used externally. 

EMBY: automatic detection requires 
1. HDHomerun protocol to be enabled
2. web-admin port on port 80
3. IP of the App is on the same primary network as Emby (Docker 172.* network does not work due to Emby broadcasting on 255.255.255.255 local network only)

EMBY: manual detection requires 
1. HDHomerun protocol to be enabled
This will work with Docker 172 networks

PLEX: automatic detection requires 
1. HDHomerun protocol enabled
2. SSDP protocol enabled
3. web-admin port on port 80
4. IP of the App is on the same primary network as Plex

PLEX: manual detection requires 
1. HDHomerun protocol enabled
This will work with Docker 172 networks

For Docker, first build the container with
`sudo docker build . -f Dockerfile_tvh_crypt.alpine -t [tag to use]`
Then to run the container
`sudo docker run -p 6077:6077  -v [location of data directory on server]:/app/data --rm [tag used earlier]`

For the config.ini file associated with Docker... there are no special changes for Docker.

**Comment by rocky4546** [comment]
There is a chance if Plex or Emby was installed in a Docker container that the ability to communicate across the 172 network between Emby/Plex and the app is possible.  This would make it possible that the automatic detection would be enabled. Complexity of the docker install of Emby/Plex is very high, so it will not be tested.

**Comment by cookieisland** [comment]
For the alpine and slim buster dockerfiles I use them with docker-compose and I provide with an ini and key file via a volume statement. That way I keep my configuration files in my docker directory and out of the source directory.  Here is what my docker-compose file looks like:

 ```
 tvheadend-locast:
    build:
      context: /home/cookieisland/source/tvheadend-locast
      dockerfile: Dockerfile_tvh_crypt.slim-buster
    image: tvheadend-locast
    container_name: tvheadend-locast
    environment:
      TZ: "America/Los_Angeles"
    network_mode: "host"
    cpu_shares: 2048
    restart: unless-stopped
    volumes:
      - /home/cookieisland/docker/tvheadend-locast/config/config.ini:/app/config/config.ini
      - /home/cookieisland/docker/tvheadend-locast/config/key.txt:/root/.locast/key.txt
```

**Comment by cookieisland** [comment]
wait - I just tried using your new commit and I am now also getting 
`ERROR: Config file missing, Exiting...`

**Comment by cookieisland** [comment]
I figured it out. After your latest commit the config.ini file now must be located in /app/config.ini.  Previously it could be located in /app/config/config.ini.  I modified my docker-compose volume statement and I am running again.  Here is my latest docker-compose.yaml that now works again.

```
tvheadend-locast:
   build:
     context: /home/cookieisland/source/tvheadend-locast
     dockerfile: Dockerfile_tvh_crypt.slim-buster
   image: tvheadend-locast
   container_name: tvheadend-locast
   environment:
     TZ: "America/Los_Angeles"
   network_mode: "host"
   cpu_shares: 2048
   restart: unless-stopped
   volumes:
     - /home/cookieisland/docker/tvheadend-locast/config/config.ini:/app/config.ini
     - /home/cookieisland/docker/tvheadend-locast/config/key.txt:/root/.locast/key.txt
```
